package etsisi.upm.myupmclassroom.persistence;

import java.util.Collection;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @MyUPMClassroom
//  @ Author : @CITSIM_22_03
//
//

import etsisi.upm.myupmclassroom.modelo.*;

public interface IPPAS {
	public void insertPAS(PAS pas);
	
	public void deletePAS(String codigo_persona);
	
	public PAS selectPAS(String codigo_persona);
	
	public void updatePAS(PAS pas);
	
	public Collection<PAS> getAll();
}
