package etsisi.upm.myupmclassroom.persistence;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @MyUPMClassroom
//  @ Author : @CITSIM_22_03
//
//

import java.sql.*;
import java.util.*;
import etsisi.upm.myupmclassroom.modelo.*;

public class PAlumno implements IPAlumno {
	
	@Override
	public void insertAlumno(Alumno alumno) {
		Statement stmt;
		
		try {
			PersistenceManager.getInstance().getPersistenceUsuario().insertUsuario(alumno);
			
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("INSERT INTO Alumno (dni, num_matricula) VALUES (" + 
					"'" + alumno.getDNI() + "'," +
					"'" + alumno.getNum_matricula() + "'" +
					")");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	@Override
	public void deleteAlumno(String num_matricula) {
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("DELETE FROM Alumno WHERE num_matricula='" + num_matricula + "'");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	@Override
	public Alumno selectAlumno(String num_matricula) {

		Alumno alumno = null;
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from Alumno where num_matricula='" + num_matricula + "'");
			
			while (rs.next())
			{
				Usuario usuario = PersistenceManager.getInstance().getPersistenceUsuario().selectUsuario(rs.getString("dni"));			
				
				alumno = new Alumno (
						rs.getString("num_matricula"),
						usuario
						);
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return alumno;
	}
	
	@Override
	public void updateAlumno(Alumno alumno) {
		// No tiene ningun campo que no sea Primary Key ni Foreign Key
	}
	
	@Override
	public Collection<Alumno> getAll() {
		
		LinkedList<Alumno> alumnolistout = new LinkedList<>();
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from Alumno");
			
			while (rs.next())
			{
				Usuario usuario = PersistenceManager.getInstance().getPersistenceUsuario().selectUsuario(rs.getString("dni"));
				
				alumnolistout.add(new Alumno(
						rs.getString("num_matricula"),
						usuario
						));
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return alumnolistout;
	}
	
	@Override
	public List<Aula> selectAulasSuscritas(String dni) {
		
		LinkedList<Aula> aulalist = new LinkedList<>();
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from AlumnoSuscribeAula where dni = '" + dni + "'");
			//ResultSet rs = stmt.executeQuery("select * from AlumnoSuscribeAula where dni = '" + selectAlumno(num_matricula).getDNI() + "'");
			
			while (rs.next()) {
				Aula aula = PersistenceManager.getInstance().getPersistenceAula().selectAula(rs.getInt("idAula"));
				
				aulalist.add(aula);
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return aulalist;
	}
}