package etsisi.upm.myupmclassroom.persistence;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @MyUPMClassroom
//  @ Author : @CITSIM_22_03
//
//

import java.sql.*;
import java.util.*;
import etsisi.upm.myupmclassroom.modelo.*;

public class PPDI implements IPPDI {
	
	@Override
	public void insertPDI(PDI pdi) {
		Statement stmt;
		try {
			PersistenceManager.getInstance().getPersistenceUsuario().insertUsuario(pdi);
			
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("INSERT INTO PDI (dni, codigo_trabajador, categoria) VALUES (" + 
					"'" + pdi.getDNI() + "'," +
					"'" + pdi.getCodigo_trabajador() + "'," +
					"'" + pdi.getCategoria() + "'" +
					")");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	@Override	
	public void deletePDI(String codigo_trabajador) {
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("DELETE FROM PDI WHERE codigo_trabajador='" + codigo_trabajador + "'");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}	
	}
	
	@Override	
	public PDI selectPDI(String codigo_trabajador) {

		PDI pdi = null;
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from PDI where codigo_trabajador='" + codigo_trabajador + "'");
			
			while (rs.next())
			{
				Usuario usuario = PersistenceManager.getInstance().getPersistenceUsuario().selectUsuario(rs.getString("dni"));
				
				pdi = new PDI (
						codigo_trabajador,
						TCategoria.valueOf(rs.getString("categoria").toUpperCase()),
						usuario
						);
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return pdi;
	}
	
	@Override	
	public void updatePDI(PDI pdi) {
		Statement stmt;
		
		try {
			PersistenceManager.getInstance().getPersistenceUsuario().updateUsuario(pdi);
			
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("UPDATE PDI SET " +
					"categoria = '" + pdi.getCategoria() + "'" +
					" WHERE codigo_trabajador='" + pdi.getCodigo_trabajador() + "' AND '" + pdi.getDNI() + "'"
					);
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public Collection<PDI> getAll() {

		LinkedList<PDI> pdilistout = new LinkedList<>();
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from PDI");
			
			while (rs.next())
			{
				Usuario usuario = PersistenceManager.getInstance().getPersistenceUsuario().selectUsuario(rs.getString("dni"));
				pdilistout.add(new PDI (
						rs.getString("codigo_trabajador"),
						TCategoria.valueOf(rs.getString("categoria").toUpperCase()),
						usuario
						));
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return pdilistout;
	}
	
	@Override
	public List<Aula> selectAulasSuscritas(String dni) {
		
		LinkedList<Aula> aulalist = new LinkedList<>();
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from AlumnoSuscribeAula where dni = '" + dni + "'");
			//ResultSet rs = stmt.executeQuery("select * from AlumnoSuscribeAula where dni = '" + selectAlumno(num_matricula).getDNI() + "'");
			
			while (rs.next()) {
				Aula aula = PersistenceManager.getInstance().getPersistenceAula().selectAula(rs.getInt("idAula"));
				
				aulalist.add(aula);
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return aulalist;
	}
}