package etsisi.upm.myupmclassroom.persistence;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @MyUPMClassroom
//  @ Author : @CITSIM_22_03
//
//

import java.sql.*;
import etsisi.upm.myupmclassroom.modelo.*;
import utilidades.Cifrado;

public class PUsuario implements IPUsuario {

	@Override
	public void insertUsuario(Usuario usuario) {
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			String contrasenyaCifrada = Cifrado.cifrar(usuario.getPassword());
			
			stmt.executeUpdate("INSERT INTO Usuario (dni, nombre, primer_apellido, segundo_apellido, correo, contrasenya) VALUES (" + 
					"'" + usuario.getDNI() + "'," + 
					"'" + usuario.getNombre() + "'," + 
					"'" + usuario.getPrimer_apellido() + "'," + 
					"'" + usuario.getSegundo_apellido() + "'," + 
					"'" + usuario.getEmail() + "'," + 
					"'" + contrasenyaCifrada + "'" +
					")");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}		
	}

	@Override
	public void deleteUsuario(String dni) {
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("DELETE FROM Usuario WHERE dni='" + dni + "'");
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}		
	}

	@Override
	public Usuario selectUsuario(String dni) {

		Usuario usuario = null;
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			ResultSet rs = stmt.executeQuery("select * from Usuario where dni='" + dni + "'");
			
			while (rs.next())
			{
				usuario = new Usuario (
						dni,
						rs.getString("nombre"),
						rs.getString("primer_apellido"),
						rs.getString("segundo_apellido"),
						rs.getString("correo"),
						rs.getString("contrasenya")
						);
			}
			
			stmt.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return usuario;
	}

	@Override
	public void updateUsuario(Usuario usuario) {
		Statement stmt;
		
		try {
			stmt = PersistenceManager.getInstance().getconnection().createStatement();
			
			stmt.executeUpdate("UPDATE Usuario SET " +
					"nombre = '" + usuario.getNombre() + "'," +
					"primer_apellido = '" + usuario.getPrimer_apellido() + "'," +
					"segundo_apellido = '" + usuario.getSegundo_apellido() + "'," +
					"correo = '" + usuario.getEmail() + "'," +
					"contrasenya = '" + usuario.getPassword() + "'" +
					" WHERE dni='" + usuario.getDNI() + "'"
					);
			
			stmt.close();
		
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}